<?php

namespace AppBundle\Repository;

/**
 * scheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class scheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
